### ISSUE TITLE
[question] Does this only sync the indexes?

### ISSUE THREAD

**Issue by chrillewoodz** [nayfin/algolia-firestore-sync#3]
I'm looking into Algolia for text searches but from what I understand there's no way to keep the realtime data sync when going via Algolia. I assume this package doesn't handle that but rather just sync the indexes?

**Comment by nayfin** [comment]
Yes, this only updates the endices. I have contacted algolia about keeping the real-time goodness of firebase when using their search engine, and it seemed like they didn't really understand my question. I think there must be some hack on the front end but I haven't discovered it yet. I do know that if you are using angular instant search library widgets, make an update in your database, algolia will get synced, your front end won't show the changes automatically,  but it will show in results if you actively search for the changed document.

**Comment by chrillewoodz** [comment]
Yeah I tried asking Firebase support too but they were of little help also. I thought of a solution where you pass a unique ID from the frontend to your Algolia search, which you then use to store the results in Firebase when you get them. And then you can create a sync based on that id. I haven't tested it yet but I can't see any reason as to why it wouldn't work.
